### ISSUE TITLE
I know it sounds vague, but "Something bad happened"

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/selecting-single-elements-readme#10]
This lesson needs serious re-review.

There's typos and grammar errors.  The 'point' of the lesson is nearly lost.  The CodePen nonsense is gone, but this is worse.

**Comment by bhollan** [comment]
Yet another student who does not understand what's happening in this lab.

**Comment by bhollan** [comment]
Maybe, if there is insistence that we use a 'static' and non-community-editable version of the Ada Lovelace page, maybe we should create a `gh-pages` branch of this repo and point a link in the `master` branch to `lovelace.html` of that branch?  That would be a way to avoid having people who are never-seen-a-line-of-code-before new think about forking/cloning/viewing extra files from a 'repo'.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
