### ISSUE TITLE
Outdated Wikipedia website

### ISSUE THREAD

**Issue by asabogal** [learn-co-curriculum/selecting-single-elements-readme#12]
The link for Charles Babbage is no longer inside the greybox. 
The .infobox selector wouldn't apply to the Charles Babbage link.
I suggest updating the lesson and task the student with selecting the image of Ada Lovelace.
This link does not have an id or class attribute and so the same principle can be applied

**Comment by kwebster2** [comment]
@ruthmesfun 
As mentioned above, it looks like the Wikipedia article has changed. There is no longer a "Charles Babbage" link in the infobox, which is currently being used for the "SELECTING BY ANCESTRY - AND SOLVING A PROBLEM" section of the lesson.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
