### ISSUE TITLE
The instructions on this page suck.

### ISSUE THREAD

**Issue by exgllo** [learn-co-curriculum/selecting-single-elements-readme#13]
Charles Babbage does not exist in the infobox nor does his birthplace.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
