### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by jecc13** [learn-co-curriculum/selecting-single-elements-readme#15]
Within the following snippet, I believe the words "look at" - or something similar - are missing after "Let's":

> SELECTING BY ANCESTRY - AND SOLVING A PROBLEM
> Let's some more content: links.

**Comment by jecc13** [comment]
Found another one...

In the SELECTING BY ANCESTRY - AND SOLVING A PROBLEM paragraph, the following sentence is missing a word between "is" and "we"... perhaps "how"?

> That is we will "chain" our calls to document.querySelector.

**Comment by jecc13** [comment]
Third possible typo on the page...

In the RETRIEVING ATTRIBUTES section, there seems to be something missing from the following sentence:

> Many of methods on this instance correspond to the potential attributes of an HTML anchor. 

Perhaps "the" is missing?

**Comment by jecc13** [comment]
Duplicate word on the page...

After "The magic of guessing" section, the following sentence has a duplicate word:

> The methods we explored thus far like like href and text make a lot of sense when we have an instance of an HTMLAnchorElement. 

The word "like" is repeated and shouldn't be.

**Comment by sgharms** [comment]
Hi, @jecc13.

Thanks for the careful proofreading. I've updated the content per your recommendations.

Thank you. I apologize for any confusion.

Steven

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team

**Comment by FernanGonzalez** [comment]
I found another typo:

> To select something by the tag name we simply "pass" through the "tag name" to **document.querySelecgtor**.

**Comment by FernanGonzalez** [comment]
Hi Steven (@sgharms ),

I am not sure how this works since this issue was closed, so I'm tagging you hoping you'll see this. I found another possible typo:

> By calling the selected element's constructor property, we can see that **we** maryleboneAnchor is an "instance" of an HTMLAnchorElement.

Best regards.

**Comment by sgharms** [comment]
Will fix next week!

**Comment by FernanGonzalez** [comment]
Thank you!
