### ISSUE TITLE
Instructions on how to access `lovelace.html` file are not clear for IDE users

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/selecting-single-elements-readme#16]
@sgharms 
The instructions regarding opening the `lovelace.html` file work fine for a student using a local environment, but it is difficult for someone using the IDE to understand what they need to do (especially the browser IDE, which is not available for this lesson). 

I think it would help to link to the help center instructions on manually opening a lab and to make the browser IDE available for this lesson, or otherwise to use some HTML renderer to render the HTML file straight from the Github repo (such as https://htmlpreview.github.io/?https://github.com/learn-co-students/selecting-single-elements-readme-bootcamp-prep-000/blob/master/lovelace.html). Or, perhaps we can serve the modified HTML file somewhere.

**Comment by sgharms** [comment]
Yeah, I recognize this one as being a bit out of sync now that we launched the awesome web-based IDE. It really is better suited for a local environment. We probably need to slot this to happen as a one-off improvement.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
