### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bnoordman** [learn-co-curriculum/selecting-single-elements-readme#20]
Typo under "Selecting Single Elements Readme" page. (Highlighted in purple.)
<img width="838" alt="screen shot 2018-01-15 at 5 35 48 pm" src="https://user-images.githubusercontent.com/17468782/34967881-993c6490-fa1a-11e7-84b1-ee83690d59e8.png">

**Comment by sgharms** [comment]
Thanks! Fix is propagating!
