### ISSUE TITLE
Console issue?

### ISSUE THREAD

**Issue by Riz3nPho3nix** [learn-co-curriculum/selecting-single-elements-readme#23]
I am getting errors in the Chrome dev console when I go to find the firstHeading. I am able to query correctly but I am not sure why I am getting the errors. I also opened the page in Firefox and got:

Loading failed for the <script> with source “https://learn-co-curriculum.github.io/w/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector”.

Here is the snip of the errors that came up in Chrome:
![lovelace](https://user-images.githubusercontent.com/30031131/35426534-5d2277b2-0229-11e8-849f-0e2b3985e70b.PNG)

**Comment by Donnadieu** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
