### ISSUE TITLE
Ada Lovelace Page

### ISSUE THREAD

**Issue by bethanyfuller** [learn-co-curriculum/selecting-single-elements-readme#25]
There are errors in the "console" tab and all the code that I enter to manipulate with Javascript, as instructed on the class webpage, only produces errors.  The results that should occur cannot occur due to the errors on the page.
Failed to load resource: the server responded with a status of 404 (Not Found)
load.php Failed to load resource: the server responded with a status of 404 (Not Found)
load.php Failed to load resource: the server responded with a status of 404 (Not Found)
poweredby_mediawiki_88x31.png Failed to load resource: the server responded with a status of 404 (Not Found)
wikimedia-button.png Failed to load resource: the server responded with a status of 404 (Not Found)
enwiki.png Failed to load resource: the server responded with a status of 404 (Not Found)
load.php Failed to load resource: the server responded with a status of 404 (Not Found)
lovelace2.css Failed to load resource: the server responded with a status of 404 (Not Found)
﻿

​Above is what is in the console tab.

Below is what happens when I enter the code as instructed:document:querySelector("#firstHeading")
VM5821:1 Uncaught ReferenceError: querySelector is not defined
    at <anonymous>:1:10

document:querySelector('h1')
VM5825:1 Uncaught ReferenceError: querySelector is not defined
    at <anonymous>:1:10

**Comment by Donnadieu** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
