### ISSUE TITLE
Marylebone

### ISSUE THREAD

**Issue by catherine-o** [learn-co-curriculum/selecting-single-elements-readme#31]
The infobox does not appear on the right side of my screen so it took me a little bit to understand what it was referring to. 

![Lovelace](https://user-images.githubusercontent.com/50638796/57801223-7e150680-7710-11e9-9a6f-a20914954b16.jpg)

**Comment by catherine-o** [comment]
Also, it is not in a 'grey inset' as mentioned in the lesson.

**Comment by ivalentine** [comment]
It looks like the element in question is now a `div`, not a `span`. Changing the selector to use `div` will work:

`document.querySelector(".infobox").querySelector("div.deathplace").querySelector("a")`

**Comment by maxwellbenton** [comment]
Hi @catherine-o,

Thank you for spotting this and providing feedback. We've updated the instructions, replacng the reference to the right side and 'gray inset' with clearer instructions, which should resolve this issue. 

Thank you for contributing to a Learn lesson!
