### ISSUE TITLE
Charles Babbage has left the building. 

### ISSUE THREAD

**Issue by Cparusso** [learn-co-curriculum/selecting-single-elements-readme#9]
In the "SELECTING BY ANCESTRY - AND SOLVING A PROBLEM" section of this lesson I noticed that when I typed "document.querySelector('.infobox').querySelector('a')" into my console I was brought to the link to the image of Ada, and not to the link for Charles Babbage as the lesson said it would. I understand how I got to the image, I just thought it was strange that the lesson seems to be incorrect. I understand that this is wikipedia and that it changes from time to time. Just wanted to point that out.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue.

Sincerely,

Flatiron Curriculum Team
